sudo: required

# install gfortran to run the model
before_install:
  - sudo apt-get install gfortran

language: r
r:
  - release
  - devel

cache: packages

# soft accept
warnings_are_errors: false

# execute the R code
install:
  - Rscript -e 'install.packages("zoo")'
script:
  - Rscript -e Figure_1.r